[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the problematic redirect that's causing all paths to go to index.html
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#   force = false
#   conditions = {Role = ["anonymous"]} 